"      _
"  _ _|_|_____ ___ ___
" | | | |     |  _|  _|
"  \_/|_|_|_|_|_| |___|
"
" This is ale's ~/.vimrc

set nocompatible

" Plugins
filetype off
call plug#begin(expand('~/.vim/plugins'))
Plug 'ackyshake/spacegray.vim'
call plug#end()

filetype plugin indent on

" Indentation
set autoindent
set noexpandtab
set tabstop=3 shiftwidth=3 softtabstop=3
autocmd FileType * setlocal
	\ noexpandtab
	\ tabstop=3 shiftwidth=3 softtabstop=3

" Appearance
syntax on
set background=dark
colorscheme spacegray
highlight Normal ctermbg=233
highlight PmenuSel ctermbg=137 ctermfg=NONE

" Cursorline
set cursorline
highlight CursorLine ctermbg=234

" Set marks
set list
set listchars=tab:\┊\ ,extends:»,precedes:«,nbsp:⎵
highlight SpecialKey ctermbg=NONE ctermfg=238

" Highlight trailing whitespaces
highlight WhiteSpaces ctermbg=red
match WhiteSpaces /\s\+$/

" Save cursor
autocmd BufReadPost * if line("'\"") | execute("normal `\"") | endif

" Behaviour
set hidden
set confirm
set fileformat=unix
set backspace=indent,eol,start
set nostartofline

if has('mouse')
	set mouse=nvc
endif

" Visual settings
set number
set scrolloff=3
set splitright
"set virtualedit=onemore

" Statusline
set wildmenu
set showcmd
set cmdheight=1
set laststatus=2
set ruler
set completeopt=longest,menuone

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Keys timeout
set notimeout ttimeout ttimeoutlen=200

" Bell
set visualbell
set t_vb=

" Mappings
nnoremap <C-L> :nohl<CR><C-L>
