"      _
"  _ _|_|_____ ___ ___
" | | | |     |  _|  _|
"  \_/|_|_|_|_|_| |___|
"
" This is ale's ~/.vimrc

set nocompatible

filetype off
call plug#begin(expand('~/.vim/plugins'))

" Plugins
"Plug 'vimsence/vimsence'
Plug 'vim-scripts/auto-pairs-gentle'
Plug 'roxma/SimpleAutoComplPop'

" Themes
Plug 'sainnhe/gruvbox-material'
Plug 'ghifarit53/tokyonight-vim'
Plug 'tomasiser/vim-code-dark'
Plug 'ackyshake/spacegray.vim'
Plug 'bluz71/vim-moonfly-colors'
Plug 'sainnhe/everforest'
Plug 'romainl/Apprentice'
Plug 'sainnhe/edge'

call plug#end()
filetype plugin indent on

" Stop AutoPairs from centering the view
let g:AutoPairsCenterLine = 0

" Add SimpleAutoComplPop support for all filetypes and file completion
let g:sacpDefaultFileTypesEnable = {}
autocmd FileType * call sacp#enableForThisBuffer({"matches": [
	\ {'=~': '\v\w{3}$', 'feedkeys': "\<C-x>\<C-n>"},
	\ {'=~': '\v\/\S*$', 'feedkeys': "\<C-x>\<C-f>", 'ignoreCompletionMode': 1}
	\ ]})

" Indentation
set autoindent
set noexpandtab
set tabstop=3 shiftwidth=3 softtabstop=3
autocmd FileType * setlocal
	\ noexpandtab
	\ tabstop=3 shiftwidth=3 softtabstop=3

" Show trailing whitespaces
autocmd ColorScheme * highlight WhiteSpaces ctermbg=red guibg=#cc6666
autocmd InsertEnter,InsertLeave,BufWinEnter * match WhiteSpaces /\s\+$/

" Appearance
syntax on
set background=dark
set cursorline
set colorcolumn=86

if &t_Co >= 256
	set termguicolors
endif
colorscheme gruvbox-material

" Show tabs
set list
set listchars=tab:\┊\ ,extends:»,precedes:«,nbsp:⎵

" Save cursor
autocmd BufReadPost * if line("'\"") | execute("normal `\"") | endif

" Behaviour
set hidden
set confirm
set fileformat=unix
set backspace=indent,eol,start
set nostartofline

if has('mouse')
	set mouse=nvc
endif

" Visual settings
set number
set scrolloff=3
set splitright
"set virtualedit=onemore

" Statusline
set wildmenu
set showcmd
set cmdheight=1
set laststatus=2
set ruler
set completeopt=longest,menuone

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Keys timeout
set notimeout ttimeout ttimeoutlen=200

" Bell
set visualbell
set t_vb=

" Clear the search highlighting and redraw the screen
nnoremap <C-L> :nohl<CR><C-L>

" Set Alt-n to Escape
"exec "set <M-n>=\en"
"noremap <M-n> <Esc>
"inoremap <M-n> <Esc>
"cnoremap <M-n> <C-\><C-n>
