"      _
"  _ _|_|_____ ___ ___
" | | | |     |  _|  _|
"  \_/|_|_|_|_|_| |___|
"
" This is ale's ~/.vimrc

set nocompatible

filetype off
call plug#begin(expand('~/.vim/plugins'))

" Plugins
"Plug 'vimsence/vimsence'
Plug 'alek3y/auto-pairs-gentle'
Plug 'alek3y/vim-auto-popmenu'
Plug 'junegunn/fzf.vim'
Plug 'iamcco/markdown-preview.nvim', {
	\ 'do': {-> mkdp#util#install()},
	\ 'for': ['vim-plug', 'markdown']}

" Themes
Plug 'sainnhe/gruvbox-material'
Plug 'ghifarit53/tokyonight-vim'
Plug 'tomasiser/vim-code-dark'
Plug 'ackyshake/spacegray.vim'
Plug 'sainnhe/everforest'
Plug 'sainnhe/edge'

call plug#end()
filetype plugin indent on

" Auto pairs settings
let g:AutoPairsCenterLine = 0	" Stop it from centering the view
let g:AutoPairsCompleteOnNonWords = 1
let g:AutoPairsCompleteNewline = 0

" Popup menu settings
let g:apc_enable_ft = {'*': 1}
let g:apc_cr_confirm = 1
let g:apc_enable_tab = 0
set completeopt=menu,menuone,noselect
set shortmess+=c

" Special keybindings (including plugins)
let mapleader = "\\"

nnoremap <leader>ff :Files<CR>
nnoremap <leader>fb :Buffers<CR>
nnoremap <leader>fw :Windows<CR>
nnoremap <leader>fl :Lines<CR>
nnoremap <leader>ft :Filetypes<CR>
nnoremap <leader>fc :Colors<CR>

nnoremap <leader>fgf :GFiles<CR>
nnoremap <leader>fgc :Commits<CR>
nnoremap <leader>fgb :BCommits<CR>

nnoremap <leader>mp :MarkdownPreview<CR>
nnoremap <leader>ms :MarkdownPreviewStop<CR>

" Clear the search highlighting and redraw the screen
nnoremap <C-L> :nohl<CR><C-L>

" Indentation
set autoindent
set noexpandtab
set tabstop=3 shiftwidth=3 softtabstop=3
autocmd FileType * setlocal
	\ noexpandtab
	\ tabstop=3 shiftwidth=3 softtabstop=3

" Show trailing whitespaces
autocmd ColorScheme * highlight WhiteSpaces ctermbg=red guibg=#cc6666
autocmd InsertEnter,InsertLeave,BufWinEnter * match WhiteSpaces /\s\+$/

" Appearance
syntax on
set background=dark
set cursorline
"set colorcolumn=86

if &t_Co >= 256
	set termguicolors
endif
colorscheme gruvbox-material

" Show tabs
set list
set listchars=tab:\┊\ ,extends:»,precedes:«,nbsp:⎵

" Save cursor
autocmd BufReadPost * if line("'\"") | execute("normal `\"") | endif

" Behaviour
set hidden
set confirm
set fileformat=unix
set backspace=indent,eol,start
set nostartofline

if has('mouse')
	set mouse=nvc
endif

" Visual settings
set number
set scrolloff=3
set splitright
set splitbelow
"set virtualedit=onemore

" Statusline
set wildmenu
set showcmd
set cmdheight=1
set laststatus=2
set ruler

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Keys timeout
set notimeout ttimeout ttimeoutlen=200

" Bell
set visualbell
set t_vb=
