#  _       _
# | |_ ___| |_ ___ ___
# | '_| .'| '_|  _|  _|
# |_,_|__,|_,_|_| |___|
#
# This is ale's ~/.config/kak/kakrc

##
# Key mappings
#

source "%val{config}/keys.kak"

##
# Text options
#

add-highlighter global/ number-lines
add-highlighter global/ wrap
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -tab "│" -lf " " -spc " " -nbsp " "
add-highlighter global/show-trailing-whitespaces regex '\h+$' 0:Error		# Thanks to @alexherbo2 (#2175)
set-option global disabled_hooks .*-trim-indent		# Thanks to @vbauerster (#2020)
set-option global scrolloff 8,5
set-option global indentwidth 0		# Use tabs
set-option global tabstop 2
set-option global incsearch true

evaluate-commands %sh{
	if [ "$TERM" = "xterm-256color" ]; then
		printf "colorscheme tomorrow-night"
	fi
}
face global LineNumbersWrapped +d@LineNumbers
face global MatchingChar +u
face global Whitespace rgb:4b4c4b+d@Default

# Remove scratch buffer placeholder
hook global BufCreate .* %{
	evaluate-commands %sh{
		if [ "$kak_bufname" = "*scratch*" ]; then
			printf "execute-keys 2X<a-d>"
		else
			printf "nop"
		fi
	}
}

##
# UI options
#

set-option -add global ui_options ncurses_assistant=cat
set-option -add global ui_options ncurses_set_title=false
set-option -add global ui_options ncurses_status_on_top=false
set-option global startup_info_version -1

set-option global modelinefmt %{ %val{bufname} {{context_info}} |  {{mode_info}}  }

##
# Replace command
#

# Disable the 'repl' command as it's annoying when replacing
hook global ClientCreate .* %{unalias global repl}

define-command -params 2 -docstring "
replace <from> <to>: replace manually with 'r' by navigating with 'n' and '<a-n>'
" replace %{
	set-register r "%arg{2}"
	set-register / "%arg{1}"
	execute-keys "<esc>/%arg{1}<ret>"
}

define-command -params 2 -docstring "
replaceall <from> <to>: replace globally what matches the `from` regex with the `to` string.
" replaceall %{
	set-register t "%reg{dquote}"
	execute-keys \%
	set-register dquote %sh{
		printf "%s" "$kak_reg_dot" | sed -z -E "s/$1/$2/g"
	}
	execute-keys "<a-d>P"
	set-register dquote "%reg{t}"
}

##
# Greetings
#

hook global ClientCreate .* %{info "Welcome ヾ(ᣔ ◡ ᣔ)"}
